---
title: "Analyzing Injuries in Professional Soccer Players"
output:
  pdf_document: default
  html_document: default
---


### by Andrea Fernandez



```{r}
Injury<-read.csv("~/Downloads/Injury.csv")
Premier.League<-read.csv("~/Downloads/Premier League.csv")
```


```{r}
library(Hmisc)
library(lattice)
library(survival)
library(Formula)
library(ggplot2)
dim(Injury)
summary(Injury$Age)

```


```{r}

which(is.na(Injury))
which(is.na(Premier.League))
str(Injury)

Injury$Date.of.Injury<-as.Date(Injury$Date.of.Injury, format= "%m/%d/%y")
head(Injury$Date.of.Injury)
```


```{r}
library(funModeling)
library(tidyverse)
library(Hmisc)
```
```{r}
freq(Injury)
Injury %>% distinct(Age, Date.of.Injury, Total.Days, Reoccurring.Injury) %>% ggplot(aes(Age, fill=Reoccurring.Injury)) + geom_histogram(position="identity", alpha=0.7) 

```
```{r}
library(tm)
library(wordcloud)
library(RColorBrewer)
text<-Premier.League$Details
docs<-Corpus(VectorSource(text))
docs<-tm_map(docs, content_transformer(tolower))
docs<-tm_map(docs, removeWords, stopwords("english"))
dtm<-TermDocumentMatrix(docs)
matrix<-as.matrix(dtm)
words<-sort(rowSums(matrix), decreasing=TRUE)
df<-data.frame(word=names(words), freq=words)
set.seed(1234)
wordcloud(words=df$word, freq = df$freq, min.freq = 1, max.words = 200, random.order = FALSE, rot.per = 0.35, colors=brewer.pal(8, "Dark2"))

```
```{r}
glimpse(Injury)
names<-c(1,2,3,4,6,8,9,10)
Injury[,names]<-lapply(Injury[,names], factor)
glimpse(Injury)
```









```{r}
Injury<-read.csv("~/Downloads/Injury.csv")
Injury$Date.of.Injury<-as.Date(Injury$Date.of.Injury, format= "%m/%d/%y")
injury.df <- Injury %>% select(Date.of.Injury, Age, Total.Days, Reoccurring.Injury)
head(injury.df)
```

```{r}
# Train Models
library(tidymodels)
set.seed(1234)
injury.split<-injury.df %>% initial_split(strata = Reoccurring.Injury)
injury.split
injury_train<-training(injury.split)
injury_test<-testing(injury.split)
injury_train
injury_test
```
```{r}
# Specifying what type of linear model we want built
lm_spec<- linear_reg() %>% set_engine(engine = "lm")
lm_spec
 # Train the model
lm_fit<-lm_spec %>% fit(Total.Days~., data=injury_train)
lm_fit
tidy(lm_fit)
```
```{r}
# Random Forest Model
library(ranger)
# Specifying what type of random forest model
rf_spec<-rand_forest(mode = "regression") %>% set_engine('ranger')
rf_spec
# Train the model
rf_fit<- rf_spec %>% fit(Total.Days ~., data=injury_train)
rf_fit
```
```{r}
# Evaluate both models
library(tidymodels)
library(stats)
library(dplyr)
library(magrittr)
# Training Data
results.train<-lm_fit %>% predict(new_data= injury_train) %>% mutate(truth=injury_train$Total.Days, model= "lm") %>% bind_rows(rf_fit %>% predict(new_data=injury_train) %>% mutate(truth=injury_train$Total.Days, model="rf"))
results.train
# Testing Data
results.test<-lm_fit %>% predict(new_data= injury_test) %>% mutate(truth=injury_test$Total.Days, model= "lm") %>% bind_rows(rf_fit %>% predict(new_data=injury_test) %>% mutate(truth=injury_test$Total.Days, model="rf"))
results.test
```

```{r}
results.train %>% group_by(model) %>% rmse(truth=truth, estimate =.pred)
results.test %>% group_by(model) %>% rmse(truth=truth, estimate =.pred)

# rf higher on testing data which is not a good model

results.test %>% mutate(train="testing") %>% bind_rows(results.train %>% mutate(train="training")) %>% ggplot(aes(truth, .pred, color=model)) + geom_abline(lty=2, color="gray80") + geom_point(alpha=0.5) + facet_wrap(~train)
```
```{r}
set.seed(1234)
injury_folds<-vfold_cv(injury_train, strata=Reoccurring.Injury)
injury_folds
injury_res<-fit_resamples(rf_spec, Total.Days~., injury_folds, control=control_resamples(save_pred = TRUE))
```
```{r}
injury_res %>% collect_metrics()
results.test %>% group_by(model) %>% rmse(truth=truth, estimate = .pred)
injury_res %>% unnest(.predictions) %>% ggplot(aes(Total.Days, .pred, color=id)) + geom_abline(lty=2, color="gray80", size=1.5) + geom_point(alpha=0.5)

```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
